node_env: 'development'
secret_service: 'ConfigServiceSecret'
url_db: 'postgres://postgres:123456@localhost:5432/config_service_db?sslmode=disable'
name_service: 'ConfigService'
port_grpc: 40054
host_grpc: 'localhost'
interval_check: '20s'
timeout_check: '15s'
grpc_clients:
    - Name: 'PermissionService'
      ServerAddress: 'localhost:50051'
      MaxRetries: 3
      Time: 20
      Timeout: 15
      PermitWithoutStream: true
      SecretInternal: 'PermissionServiceSecret'

permission_service_addr: 'localhost:50051'

db_cache:
  addr: "localhost:6379"
  db: 1
  password: ""
  max_idle: 10
  max_active: 100
  idle_timeout: 240
  network: "tcp"
